### PR TITLE
When deleting a contribution SET NULL contribution_id in civicrm_account_invoice instead of throwing constraint error

### PR DESCRIPTION
**Pull request by mattwire**
When this extension was created `civicrm_account_contact` was created with "CASCADE" on delete of a contact but `civicrm_account_invoice` was created with "RESTRICT" on delete of a contribution. The result is that if you have permission to delete a contribution it won't work (you'll get a 500 internal server error) because the database will throw an exception.

While there has been an ongoing discussion about whether you should be allowed to delete a contribution or not this doesn't seem like the place to restrict it as it creates a pretty poor user experience (CiviCRM appears broken).

Ping @eileenmcnaughton @jitendrapurohit @agileware-justin @agileware-fj 

This does not include an upgrader step - it will only apply for new installs - which seems ok because existing installs have probably either hit the problem and worked around it or it's not an issue.

@eileenmcnaughton Per discussion SET NULL works and I've updated this PR to do this.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire I wonder if we should set null instead - since the table does support the idea of tracking Xero invoices that do not have civi contributions

**Comment by mattwire** [comment]
@eileenmcnaughton I'd be happy with that - we'd need to take off the unique index as well though I think - I'm not completely on top of how the table is used.

**Comment by eileenmcnaughton** [comment]
@mattwire do we? I thought NULL was OK on a unique index field?

**Comment by mattwire** [comment]
@eileenmcnaughton Per discussion SET NULL works and I've updated this PR to do this.

**Comment by eileenmcnaughton** [comment]
Thanks @mattwire - I think there is a case for not allowing synced contributions to be deleted  but this doesn't seem like the right place. (Also synced contributions that are voided or cancelled would need to be excluded - so all in all that would be a complicated piece of work that no-one seems to be asking for.)

Merging this as I agree it makes sense

**Comment by mattwire** [comment]
@eileenmcnaughton I think you forgot to click merge :-)

**Comment by eileenmcnaughton** [comment]
erm yep

**Comment by agileware-justin** [comment]
Good job @mattwire, legend :)

**Pull request merged**
