### PR TITLE
Regenerate DAO and make more fields available to formbuilder

### PR DESCRIPTION
**Pull request by mattwire**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire I think you are making these available to form builder for purposes of exposing as filters? I'm wondering if some of them should be read-only cos we really don't want users editing the ones like plugin do we?

**Comment by mattwire** [comment]
@eileenmcnaughton That's the idea yes. Ok I've reviewed and pushed a better set of readonly flags. See if you agree :-)

**Comment by eileenmcnaughton** [comment]
@mattwire I think the json blob fields should probably be read only too....

**Comment by mattwire** [comment]
> @mattwire I think the json blob fields should probably be read only too....

Makes sense - updated

**Pull request merged**
