### PR TITLE
Refs #17. Try to handle mismatches.

### PR DESCRIPTION
**Pull request by xurizaemon**
See #17

### CODE REVIEW

**Comment by xurizaemon** [comment]
@eileenmcnaughton did you see this?

**Comment by eileenmcnaughton** [comment]
yeah - I just can't figure out how to get the errors at the moment - I took that off yes to try it

**Comment by eileenmcnaughton** [comment]
well yeah - but on which contribution? I went through them & tried calling AccountInvoice.getderived on each of them & didn't get the error - I noted on the redmine

**Comment by jusfreeman** [comment]
Close this PR? Pretty old.

Sorry, @xurizaemon

**Pull request closed without merging**
